window.PORTFOLIO_EXTRAS = {
  ru: {
    navExtra: "Ещё работы",
    casesNoteTitle: "Это витрина, а не полный список",
    casesNote:
      "Ниже показаны наиболее понятные работодателю примеры. Реальный объём шире: задачи от руководства и пользователей я разбирал по сути, самостоятельно формализовал и доводил до рабочего результата, даже когда запрос звучал странно, был разовым или не имел готового технического задания.",
    extraLabel: "ДОПОЛНИТЕЛЬНЫЕ РЕАЛИЗОВАННЫЕ ЗАДАЧИ",
    extraTitle: "Ещё 18 примеров прикладной автоматизации",
    extraIntro:
      "Небольшие инструменты часто дают бизнесу не меньше пользы, чем крупные проекты: убирают повторяющиеся действия, снижают риск ошибок и возвращают сотрудникам рабочее время.",
    resultLabel: "Эффект",
    stackLabel: "Технологии",
    pdfBadge: "ОДИН УНИВЕРСАЛЬНЫЙ ДОКУМЕНТ",
    pdfHint: "PDF · подробный опыт · ключевые проекты · навыки",
    pdfTitle: "Полное резюме для технического руководителя и HR",
    pdfText:
      "Единое расширенное резюме объединяет разработку 1С, бизнес-анализ, интеграции, поддержку корпоративных систем и опыт реальных процессов склада и логистики.",
    contactText:
      "Открыт к предложениям в Сербии: 1С-разработка, ERP/Application Support, бизнес-анализ и интеграционные задачи. Готов к офису, гибриду или удалённой работе.",
    secondEmail: "Дополнительная почта",
    extras: [
      {
        id: "CASE-007",
        title: "Извлечение DataMatrix из XML",
        text: "Локальный инструмент разбирает входящий XML, извлекает коды маркировки, очищает строки и формирует готовый TXT/CSV для дальнейшей проверки.",
        result: "Ручное копирование кодов из технических файлов заменено повторяемой операцией.",
        stack: "XML · JavaScript · TXT · CSV · DataMatrix",
      },
      {
        id: "CASE-008",
        title: "Поиск и удаление дублей",
        text: "Проверка объединённых списков кодов, вывод статистики повторов и формирование очищенного файла без передачи данных внешним сервисам.",
        result: "Снижено количество ошибок при загрузках и сверках маркированной продукции.",
        stack: "JavaScript · File API · Set/Map · CSV/TXT",
      },
      {
        id: "CASE-009",
        title: "Исключение списанных и возвращённых кодов",
        text: "Сравнение исходного набора с файлами списаний и возвратов, фиксация найденных совпадений и подготовка остатка для следующей операции.",
        result: "Операторы не отправляют повторно коды, которые уже выбыли из рабочего контура.",
        stack: "DataMatrix · CSV · TXT · контроль множеств",
      },
      {
        id: "CASE-010",
        title: "Разделение партий, пачек и блоков",
        text: "Инструменты делят большие наборы по правилам операции, контролируют размер частей и формируют файлы с понятными именами и итогами.",
        result: "Подготовка партий стала быстрее и предсказуемее, без ручной нарезки файлов.",
        stack: "JavaScript · File API · DataMatrix · batch processing",
      },
      {
        id: "CASE-011",
        title: "CSV для операций в «Честном знаке»",
        text: "Преобразование исходных таблиц в требуемую структуру: нормализация строк, разделители, заголовки, контроль пустых значений и итоговый файл.",
        result: "Сотрудник получает готовый файл вместо ручной пересборки таблицы перед каждой загрузкой.",
        stack: "CSV · TXT · JavaScript · валидация данных",
      },
      {
        id: "CASE-012",
        title: "Многостраничные печатные формы",
        text: "Разработка и доработка ТТН, складских и торговых форм: реквизиты, подписанты, итоги, переносы страниц и массовое формирование PDF.",
        result: "Документы формируются из учётных данных без повторного ручного заполнения.",
        stack: "1С · табличный документ · макеты · печатные формы · PDF",
      },
      {
        id: "CASE-013",
        title: "Сопровождение обменов между базами",
        text: "Разбор расхождений, доработка планов обмена и правил КД 2.1, контроль XML-обмена и восстановление корректного движения данных.",
        result: "Пользователи быстрее возвращаются к работе, а ошибки не маскируются ручными правками.",
        stack: "1С · КД 2.1 · планы обмена · XML",
      },
      {
        id: "CASE-014",
        title: "СКД-отчёты для руководителей",
        text: "Сбор данных из документов и регистров, сложные соединения, отборы, группировки и аналитические разрезы под конкретный управленческий вопрос.",
        result: "Руководители получают ответ в отчёте, а не собирают его вручную из нескольких выгрузок.",
        stack: "СКД · язык запросов 1С · регистры · Excel",
      },
      {
        id: "CASE-015",
        title: "Excel/VBA-автоматизация в логистике",
        text: "До перехода в разработку создавал сверки, отчёты и макросы для актов, складских остатков, инвентаризаций и движения товара.",
        result: "Практический опыт бизнеса стал основой для решений, которыми реально удобно пользоваться.",
        stack: "Excel · VBA · логистика · складской учёт",
      },
      {
        id: "CASE-016",
        title: "Поддержка и доработка после запуска",
        text: "Разбор обращений пользователей, уточнение сценариев, тестирование в отдельных базах, объяснение логики и улучшение решения по обратной связи.",
        result: "Разработка не заканчивается кодом: инструмент встраивается в ежедневный процесс.",
        stack: "1С Support · внедрение · инструкции · QA mindset",
      },
      {
        id: "CASE-017",
        title: "Авторизация и получение токенов API",
        text: "Реализовывал получение токенов, передачу заголовков и параметров, разбор ответов и повторное выполнение запросов для интеграций с внешними сервисами.",
        result: "Интеграция работает из 1С без ручного получения служебных данных пользователем.",
        stack: "1С · БСП · HTTP · JSON · token auth",
      },
      {
        id: "CASE-018",
        title: "Фоновые загрузки с FTP",
        text: "Настраивал регулярное получение файлов, проверку новых данных, разбор содержимого и запись результата в информационную базу без блокировки работы пользователей.",
        result: "Данные поступают в учётный контур автоматически и доступны к началу рабочего анализа.",
        stack: "1С · FTP · фоновые задания · JSON · журналирование",
      },
      {
        id: "CASE-019",
        title: "Автоматическая рассылка отчётов",
        text: "Формировал отчёт по расписанию, подготавливал представление результата и отправлял его ответственным сотрудникам без ручного запуска.",
        result: "Регулярная информация приходит адресатам вовремя и в одинаковом формате.",
        stack: "1С · регламентные задания · СКД · email",
      },
      {
        id: "CASE-020",
        title: "Массовая обработка документов",
        text: "Создавал обработки для отбора документов по организации, периоду и статусу, выполнения контролируемых действий и вывода протокола по каждой строке.",
        result: "Повторяющаяся работа с группой документов выполняется одним управляемым запуском.",
        stack: "1С · управляемые формы · запросы · табличные части",
      },
      {
        id: "CASE-021",
        title: "Контроль и обновление идентификаторов",
        text: "Искал отсутствующие или некорректные идентификаторы в связанных данных, сопоставлял записи и подготавливал безопасное массовое обновление.",
        result: "Снижено число ошибок, возникающих из-за несвязанных документов и внешних сущностей.",
        stack: "1С · регистры сведений · запросы · интеграционные ID",
      },
      {
        id: "CASE-022",
        title: "Подготовка возвратов и списаний",
        text: "Собирал и сверял списки кодов для операций возврата и списания, разделял входные данные по назначению и формировал проверяемый результат.",
        result: "Сложная файловая операция стала понятной последовательностью с контролем итогового количества.",
        stack: "DataMatrix · CSV · TXT · сверка наборов · валидация",
      },
      {
        id: "CASE-023",
        title: "Объединение файлов и контроль итогов",
        text: "Инструменты принимают несколько входных файлов, нормализуют строки, объединяют данные, считают результат и отдельно показывают спорные записи.",
        result: "Сотрудники работают с одним проверенным результатом вместо ручной склейки файлов.",
        stack: "JavaScript · File API · CSV/TXT · контроль качества",
      },
      {
        id: "CASE-024",
        title: "Инструкции и передача решения пользователям",
        text: "Описывал назначение, последовательность действий, ограничения и разбор типовых ошибок, затем объяснял решение сотрудникам на реальных сценариях.",
        result: "Новый инструмент быстрее принимается командой и требует меньше повторных обращений.",
        stack: "документация · обучение · внедрение · пользовательская поддержка",
      },
    ],
  },
  en: {
    navExtra: "More work",
    casesNoteTitle: "A showcase, not the complete list",
    casesNote:
      "The cases below are the clearest examples for an employer. The actual scope is broader: I investigated requests from managers and users, clarified the real process, translated poorly defined or unusual requests into workable requirements, and delivered the result to production.",
    extraLabel: "ADDITIONAL DELIVERED WORK",
    extraTitle: "18 more examples of practical automation",
    extraIntro:
      "Small internal tools can create as much value as large projects: they remove repetitive work, reduce errors and return productive time to employees.",
    resultLabel: "Impact",
    stackLabel: "Technology",
    pdfBadge: "ONE UNIVERSAL DOCUMENT",
    pdfHint: "PDF · detailed experience · key projects · skills",
    pdfTitle: "Complete CV for engineering managers and HR",
    pdfText:
      "One detailed CV combines 1C development, business analysis, integrations, corporate application support and hands-on knowledge of warehouse and logistics processes.",
    contactText:
      "Open to opportunities in Serbia: 1C development, ERP/Application Support, business analysis and integration work. Available for office, hybrid or remote work.",
    secondEmail: "Additional email",
    extras: [
      {
        id: "CASE-007",
        title: "DataMatrix extraction from XML",
        text: "A local tool parses incoming XML, extracts marking codes, normalizes rows and creates a clean TXT/CSV file for further verification.",
        result: "Manual copying from technical files was replaced with a repeatable operation.",
        stack: "XML · JavaScript · TXT · CSV · DataMatrix",
      },
      {
        id: "CASE-008",
        title: "Duplicate detection and cleanup",
        text: "Checks merged code lists, reports duplicate statistics and creates a clean output without sending business data to external services.",
        result: "Reduced errors in marking uploads and reconciliation workflows.",
        stack: "JavaScript · File API · Set/Map · CSV/TXT",
      },
      {
        id: "CASE-009",
        title: "Excluding written-off and returned codes",
        text: "Compares source data with write-off and return files, records matches and prepares the valid remainder for the next operation.",
        result: "Operators avoid resubmitting codes that have already left the working flow.",
        stack: "DataMatrix · CSV · TXT · set comparison",
      },
      {
        id: "CASE-010",
        title: "Splitting batches, packs and blocks",
        text: "Tools split large datasets by operational rules, validate part sizes and generate clearly named files with summary totals.",
        result: "Batch preparation became faster and predictable, without manual file cutting.",
        stack: "JavaScript · File API · DataMatrix · batch processing",
      },
      {
        id: "CASE-011",
        title: "CSV preparation for Chestny ZNAK",
        text: "Transforms source tables into the required structure: row normalization, delimiters, headers, empty-value checks and final export.",
        result: "Employees receive a ready-to-upload file instead of rebuilding a spreadsheet each time.",
        stack: "CSV · TXT · JavaScript · data validation",
      },
      {
        id: "CASE-012",
        title: "Complex multi-page print forms",
        text: "Built and refined waybills, warehouse and sales forms with requisites, signatories, totals, page breaks and bulk PDF generation.",
        result: "Documents are produced directly from accounting data without repeated manual entry.",
        stack: "1C · tabular documents · layouts · print forms · PDF",
      },
      {
        id: "CASE-013",
        title: "Data exchange support between databases",
        text: "Investigated discrepancies, refined exchange plans and Conversion 2.1 rules, checked XML flows and restored consistent data movement.",
        result: "Users return to work faster and issues are resolved at the source.",
        stack: "1C · Conversion 2.1 · exchange plans · XML",
      },
      {
        id: "CASE-014",
        title: "DCS reports for management",
        text: "Combines documents and registers through joins, filters, grouping and analytical dimensions tailored to a concrete management question.",
        result: "Managers receive an answer in one report instead of assembling several exports.",
        stack: "DCS · 1C query language · registers · Excel",
      },
      {
        id: "CASE-015",
        title: "Excel/VBA automation in logistics",
        text: "Before moving into development, created reconciliations, reports and macros for acts, stock, inventories and goods movement.",
        result: "Hands-on business experience became the foundation for tools people can actually use.",
        stack: "Excel · VBA · logistics · warehouse operations",
      },
      {
        id: "CASE-016",
        title: "Support and iteration after release",
        text: "Handles user feedback, clarifies edge cases, tests in separate databases, explains system logic and improves solutions after launch.",
        result: "Delivery does not stop at code: the tool becomes part of daily work.",
        stack: "1C Support · implementation · documentation · QA mindset",
      },
      {
        id: "CASE-017",
        title: "API authorization and token handling",
        text: "Implemented token retrieval, request headers and parameters, response parsing and controlled retries for integrations with external services.",
        result: "The integration works from 1C without users manually obtaining service credentials.",
        stack: "1C · BSP · HTTP · JSON · token auth",
      },
      {
        id: "CASE-018",
        title: "Background imports from FTP",
        text: "Scheduled file retrieval, new-data checks, content parsing and database writes without blocking everyday user work.",
        result: "Operational data arrives automatically and is ready for analysis at the start of the work cycle.",
        stack: "1C · FTP · background jobs · JSON · logging",
      },
      {
        id: "CASE-019",
        title: "Scheduled report delivery",
        text: "Generated reports on a schedule, prepared a consistent presentation and delivered results to responsible employees without manual launch.",
        result: "Recurring information reaches the right people on time and in a stable format.",
        stack: "1C · scheduled jobs · DCS · email",
      },
      {
        id: "CASE-020",
        title: "Bulk document processing",
        text: "Built processors that select documents by company, period and status, perform controlled actions and show a protocol for every record.",
        result: "Repetitive work across many documents is completed through one manageable run.",
        stack: "1C · managed forms · queries · tabular sections",
      },
      {
        id: "CASE-021",
        title: "Identifier control and updates",
        text: "Located missing or incorrect identifiers in connected data, matched records and prepared a controlled bulk update.",
        result: "Reduced failures caused by documents and external entities that were not linked correctly.",
        stack: "1C · information registers · queries · integration IDs",
      },
      {
        id: "CASE-022",
        title: "Return and write-off preparation",
        text: "Collected and reconciled marking-code lists for returns and write-offs, separated source data by operation and produced a verifiable output.",
        result: "A complex file workflow became a clear sequence with totals at every stage.",
        stack: "DataMatrix · CSV · TXT · set comparison · validation",
      },
      {
        id: "CASE-023",
        title: "File merging and total control",
        text: "Tools accept multiple files, normalize rows, merge datasets, calculate totals and isolate questionable records for review.",
        result: "Employees work with one verified result instead of manually joining files.",
        stack: "JavaScript · File API · CSV/TXT · data quality",
      },
      {
        id: "CASE-024",
        title: "User instructions and solution handover",
        text: "Documented purpose, action sequence, limitations and common errors, then explained the solution using real work scenarios.",
        result: "New tools are adopted faster and require fewer repeated support requests.",
        stack: "documentation · training · implementation · user support",
      },
    ],
  },
  sr: {
    navExtra: "Još radova",
    casesNoteTitle: "Ovo je izbor primera, ne potpuna lista",
    casesNote:
      "U nastavku su primeri koji poslodavcu najjasnije pokazuju način rada. Stvarni obim je širi: zahteve rukovodilaca i korisnika analizirao sam po suštini, pretvarao nejasne ili neobične ideje u radne zahteve i dovodio rešenje do produkcije.",
    extraLabel: "DODATNO REALIZOVANI ZADACI",
    extraTitle: "Još 18 primera praktične automatizacije",
    extraIntro:
      "Mali interni alati često daju jednaku vrednost kao veliki projekti: uklanjaju ponavljajući rad, smanjuju greške i vraćaju zaposlenima radno vreme.",
    resultLabel: "Efekat",
    stackLabel: "Tehnologije",
    pdfBadge: "JEDAN UNIVERZALNI DOKUMENT",
    pdfHint: "PDF · detaljno iskustvo · ključni projekti · veštine",
    pdfTitle: "Kompletan CV za tehničke rukovodioce i HR",
    pdfText:
      "Jedan detaljan CV objedinjuje 1C razvoj, poslovnu analizu, integracije, podršku poslovnim aplikacijama i praktično razumevanje skladišnih i logističkih procesa.",
    contactText:
      "Otvoren sam za prilike u Srbiji: 1C razvoj, ERP/Application Support, poslovna analiza i integracije. Dostupan sam za rad iz kancelarije, hibridno ili na daljinu.",
    secondEmail: "Dodatni imejl",
    extras: [
      {
        id: "CASE-007",
        title: "Izdvajanje DataMatrix kodova iz XML-a",
        text: "Lokalni alat parsira ulazni XML, izdvaja kodove, normalizuje redove i formira čist TXT/CSV za dalju proveru.",
        result: "Ručno kopiranje kodova zamenjeno je ponovljivom operacijom.",
        stack: "XML · JavaScript · TXT · CSV · DataMatrix",
      },
      {
        id: "CASE-008",
        title: "Pronalaženje i uklanjanje duplikata",
        text: "Proverava objedinjene liste, prikazuje statistiku ponavljanja i formira očišćen fajl bez slanja podataka eksternim servisima.",
        result: "Smanjene su greške pri učitavanju i usklađivanju označene robe.",
        stack: "JavaScript · File API · Set/Map · CSV/TXT",
      },
      {
        id: "CASE-009",
        title: "Isključivanje otpisanih i vraćenih kodova",
        text: "Poredi početni skup sa fajlovima otpisa i povrata, beleži podudaranja i priprema važeći ostatak za sledeću operaciju.",
        result: "Operateri ne šalju ponovo kodove koji su već izašli iz radnog toka.",
        stack: "DataMatrix · CSV · TXT · poređenje skupova",
      },
      {
        id: "CASE-010",
        title: "Deljenje partija, paketa i blokova",
        text: "Alati dele velike skupove prema pravilima operacije, proveravaju veličinu delova i formiraju jasno imenovane fajlove sa zbirnim podacima.",
        result: "Priprema partija je brža i predvidljivija, bez ručnog sečenja fajlova.",
        stack: "JavaScript · File API · DataMatrix · batch processing",
      },
      {
        id: "CASE-011",
        title: "Priprema CSV-a za Chestny ZNAK",
        text: "Pretvara izvorne tabele u potrebnu strukturu: normalizacija redova, separatori, zaglavlja, kontrola praznih vrednosti i završni izvoz.",
        result: "Zaposleni dobija fajl spreman za učitavanje umesto ručne izrade tabele.",
        stack: "CSV · TXT · JavaScript · validacija podataka",
      },
      {
        id: "CASE-012",
        title: "Složene višestranične štampane forme",
        text: "Razvoj i dorada tovarnih listova, skladišnih i prodajnih obrazaca sa podacima, potpisnicima, sumama, prelomima i masovnim PDF izvozom.",
        result: "Dokumenti se formiraju iz knjigovodstvenih podataka bez ponovnog ručnog unosa.",
        stack: "1C · tabelarni dokument · makete · štampa · PDF",
      },
      {
        id: "CASE-013",
        title: "Podrška razmeni između baza",
        text: "Analiza razlika, dorada planova razmene i pravila Konverzije 2.1, kontrola XML toka i vraćanje doslednog kretanja podataka.",
        result: "Korisnici se brže vraćaju radu, a problem se rešava u izvoru.",
        stack: "1C · Konverzija 2.1 · planovi razmene · XML",
      },
      {
        id: "CASE-014",
        title: "DCS izveštaji za rukovodioce",
        text: "Spajanje dokumenata i registara, filteri, grupisanje i analitičke dimenzije prilagođene konkretnom poslovnom pitanju.",
        result: "Rukovodioci dobijaju odgovor u jednom izveštaju umesto sklapanja više izvoza.",
        stack: "DCS · 1C upiti · registri · Excel",
      },
      {
        id: "CASE-015",
        title: "Excel/VBA automatizacija u logistici",
        text: "Pre prelaska u razvoj pravio sam usklađivanja, izveštaje i makroe za akte, zalihe, inventure i kretanje robe.",
        result: "Praktično poslovno iskustvo postalo je osnova za alate koje ljudi zaista mogu da koriste.",
        stack: "Excel · VBA · logistika · skladište",
      },
      {
        id: "CASE-016",
        title: "Podrška i dorada nakon puštanja",
        text: "Obrada povratnih informacija korisnika, pojašnjenje scenarija, testiranje u odvojenim bazama, objašnjenje logike i dalja dorada.",
        result: "Isporuka se ne završava kodom: alat postaje deo svakodnevnog rada.",
        stack: "1C Support · implementacija · uputstva · QA mindset",
      },
      {
        id: "CASE-017",
        title: "API autorizacija i upravljanje tokenima",
        text: "Implementirao sam dobijanje tokena, zaglavlja i parametre zahteva, obradu odgovora i kontrolisano ponavljanje poziva ka eksternim servisima.",
        result: "Integracija radi iz 1C bez ručnog dobijanja servisnih podataka.",
        stack: "1C · BSP · HTTP · JSON · token auth",
      },
      {
        id: "CASE-018",
        title: "Pozadinsko učitavanje sa FTP-a",
        text: "Podešavao sam periodično preuzimanje fajlova, proveru novih podataka, parsiranje sadržaja i upis u bazu bez blokiranja korisnika.",
        result: "Podaci automatski ulaze u sistem i spremni su za analizu na početku radnog ciklusa.",
        stack: "1C · FTP · pozadinski zadaci · JSON · logovanje",
      },
      {
        id: "CASE-019",
        title: "Automatska distribucija izveštaja",
        text: "Formirao sam izveštaje po rasporedu, pripremao stabilan prikaz i slao rezultate odgovornim zaposlenima bez ručnog pokretanja.",
        result: "Redovne informacije stižu pravim ljudima na vreme i u istom formatu.",
        stack: "1C · zakazani zadaci · DCS · email",
      },
      {
        id: "CASE-020",
        title: "Masovna obrada dokumenata",
        text: "Razvijao sam obrade koje biraju dokumente po kompaniji, periodu i statusu, izvršavaju kontrolisane radnje i prikazuju protokol za svaki zapis.",
        result: "Ponavljajući rad nad grupom dokumenata završava se jednim upravljanim pokretanjem.",
        stack: "1C · upravljane forme · upiti · tabelarni delovi",
      },
      {
        id: "CASE-021",
        title: "Kontrola i ažuriranje identifikatora",
        text: "Pronalazio sam nedostajuće ili netačne identifikatore, povezivao zapise i pripremao kontrolisano masovno ažuriranje.",
        result: "Smanjen je broj grešaka zbog nepovezanih dokumenata i eksternih entiteta.",
        stack: "1C · registri informacija · upiti · integracioni ID",
      },
      {
        id: "CASE-022",
        title: "Priprema povrata i otpisa",
        text: "Prikupljao sam i usklađivao liste kodova za povrat i otpis, razdvajao ulazne podatke po nameni i formirao proverljiv rezultat.",
        result: "Složen rad sa fajlovima postao je jasna sekvenca sa kontrolom ukupnog broja.",
        stack: "DataMatrix · CSV · TXT · poređenje skupova · validacija",
      },
      {
        id: "CASE-023",
        title: "Spajanje fajlova i kontrola zbira",
        text: "Alati prihvataju više fajlova, normalizuju redove, spajaju podatke, računaju rezultat i izdvajaju sporne zapise.",
        result: "Zaposleni rade sa jednim proverenim rezultatom umesto ručnog spajanja.",
        stack: "JavaScript · File API · CSV/TXT · kvalitet podataka",
      },
      {
        id: "CASE-024",
        title: "Uputstva i predaja rešenja korisnicima",
        text: "Opisivao sam svrhu, korake, ograničenja i tipične greške, a zatim objašnjavao rešenje na stvarnim radnim scenarijima.",
        result: "Novi alat se brže usvaja i zahteva manje ponovljenih zahteva za podršku.",
        stack: "dokumentacija · obuka · implementacija · korisnička podrška",
      },
    ],
  },
};
